components:
  parameters:
    aoi:
      name: aoi
      in: query
      required: true
      type: string
      description: Area of Interest (The member state or region code).
    year:
      name: year
      in: query
      required: true
      type: integer
      format: int32
      minimum: 1990
      maximum: 2030
      default: 2020
      description: The year of parcels dataset.
    pid:
      name: pid
      in: query
      required: true
      type: string
      description: The parcel ID.
    lat:
      name: lat
      in: query
      required: true
      type: number
      format: float
      description: Latitude in decimal degrees.
    lon:
      name: lon
      in: query
      required: true
      type: string
      description: Longitude in decimal degrees.
    poly:
      name: poly
      in: query
      required: true
      type: string
      description: Returns a list of parcel within a given polygon.
    ptype:
      name: ptype
      in: query
      required: false
      type: string
      description: Parcel type (use only in case there are separate parcel tables of the same year dedicated to different type of analyses or for different regions).
    withGeometry:
      name: withGeometry
      in: query
      required: false
      type: string
      default: "True"
      enum: ["True", "False"]
      description: Include the parcel geometry
    tstype:
      name: tstype
      in: query
      required: false
      type: string
      default: "s2"
      enum: [s2, bs, c6, scl]
      description: s2:Sentinel-2 Level 2A, bs:S1 CARD Backscattering Coefficients, c6:S1 CARD 6-day Coherence, scl:Scene classification layer.
    scl:
      name: scl
      in: query
      required: false
      type: string
      default: "True"
      enum: ["True", "False"]
      description: Include scl in the s2 extraction, for use in cloud screening.
    ref:
      name: ref
      in: query
      required: false
      type: string
      default: "False"
      enum: ["True", "False"]
      description: Include Sentinel image reference in time series.
    band:
      name: band
      in: query
      required: false
      type: string
      default: "B08"
      enum: [B02, B03, B04, B08, B05, B06, B07, B8A, B11, B12, SCL]
      description: Sentinel-2 band name. One of [‘B02’, ‘B03’, ‘B04’, ‘B08’] (10 m bands) or [‘B05’, ‘B06’, ‘B07’, ‘B8A’, ‘B11’, ‘B12’, ‘SCL’] (20 m bands).
    start_date:
      name: start_date
      default: "01-01-2019"
      in: query
      required: true
      type: string
      description: Time window for which Level-2A Sentinel-2 is available (after 27 March 2018).
    end_date:
      name: end_date
      default: "01-06-2019"
      in: query
      required: true
      type: string
      description: Time window for which Level-2A Sentinel-2 is available (after 27 March 2018).
    chipsize:
      name: chipsize
      default: 512
      in: query
      required: false
      type: integer
      format: int32
      description: Size of the chip in pixels. Defaults '512’. Cannot be larger than ‘5120’.
    extend:
      name: extend
      default: 512
      in: query
      required: false
      type: number
      format: float
      description: Size of the chip in meters (the effective resolution of the chip is extend/chipsize).
    plevel:
      name: plevel
      in: query
      required: false
      type: string
      default: LEVEL2A
      enum: [LEVEL2A, LEVEL1C]
      description: ‘LEVEL2A’ (default), ‘LEVEL1C’. Use LEVEL1C where LEVEL2A is not avaiable.
    tms:
      name: tms
      default: Google
      in: query
      required: false
      type: string
      description: Google (default), Bing
    iformat:
      name: iformat
      in: query
      required: false
      type: string
      default: tif
      enum: [tif, png]
      description: Google (default), Bing
    distance:
      name: distance
      default: 1000.0
      in: query
      required: false
      type: number
      format: float
      minimum: 1
      maximum: 5000.0
      description: Distance in meters. Defaults to 1000.0 (MAX 5000.0).
    maxPeers:
      name: maxPeers
      default: 10
      in: query
      required: false
      type: integer
      format: int32
      minimum: 1
      maximum: 100
      description: Number of parcels to return MAX 100.
